feat(nfts): add support for NFTs
Apillon-web3/sdk pull request #2
Opened 2023-07-27 07:14 UTC by tad3j

2023-08-09 13:21 UTC, tinemlakar requested changes

2023-08-09 13:21 UTC, tinemlakar commented on packages/sdk/src/lib/common.ts
> +    return undefined;
This will never happen as `!undefined === true` !

2023-08-09 13:21 UTC, tinemlakar commented on packages/sdk/src/lib/common.ts
> +  return value === 'true' || value === '1';
`return value === 'true' || value == 1 || !!value;`

2023-08-09 13:46 UTC, tad3j commented on packages/cli/src/lib/files.ts
> +      return;
I avoided it so we don't show stack trace to CLI user but just the error. Should we do that?

2023-08-09 13:49 UTC, tad3j commented on packages/cli/src/lib/types.ts
> +export interface Globals {
`commander` calls them `optsWithGlobals` so I used that name. Will change.

2023-08-10 08:04 UTC, tinemlakar approved these changes

2023-08-10 08:04 UTC, merged